version: "3.7"
services: 
  web:
    build: web
    restart: always
    ports: 
      - 5000:5000
    environment:
      - DEBUG=1
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
  
  db:
    image: postgres:13
    restart: always
    ports: 
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - POSTGRES_DB=market
    volumes:
      - postgres_data:/

networks:
  flask_network:
    